### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by hsnice16** [hsnice16/PoshUI-Documentation#30]
#### Currently, the code does not check the users' default theme preference. It only allows toggling themes via the moon button on site. Using codes below,

```css
/* app.css */

/** Dark Theme **/

[data-theme="dark"] {
  --COLOR-BACKGROUND: #22272e;
  --COLOR-CODE-BG: #2d333b;
  --COLOR-TEXT: #adbac7;
  --COLOR-TEXT-300: #8d97a0;
}

[data-theme="dark"] .text-slate-800 {
  color: var(--COLOR-TEXT);
}

[data-theme="dark"] .btn-home {
  box-shadow: 0.1rem 0.1rem 0.5rem var(--COLOR-TEXT-300);
}

[data-theme="dark"] .component-container {
  background: var(--COLOR-CODE-BG);
  border-color: var(--COLOR-CODE-BG);
}

[data-theme="dark"] :is(.card, .grid, .modal, .stacked-list li) {
  color: var(--COLOR-BACKGROUND);
}

[data-theme="dark"] .badge-btn {
  color: var(--COLOR-TEXT);
}

[data-theme="dark"] :is(table, tr) {
  border-color: var(--COLOR-BACKGROUND);
}

[data-theme="dark"] tbody tr:nth-child(even) {
  background: var(--COLOR-BACKGROUND);
}
```

#### And
```javascript
// js/app.js

const btnTheme = document.querySelector(".btn-theme");
const htmlElement = document.documentElement;
const moonIcon = document.querySelector(".btn-theme .fa-moon");

btnTheme.addEventListener("click", () => {
  if (!htmlElement.hasAttribute("data-theme")) {
    htmlElement.setAttribute("data-theme", "dark");
    localStorage.setItem("poshUITheme", "dark");
  } else {
    htmlElement.removeAttribute("data-theme");
    localStorage.removeItem("poshUITheme");
  }

  moonIcon.classList.toggle("fas");
});

(() => {
  const theme = localStorage.getItem("poshUITheme");

  if (theme) {
    htmlElement.setAttribute("data-theme", "dark");
    moonIcon.classList.add("fas");
  }
})();

```

#### Add code to check user default theme preference
